### PR TITLE
Tab Mix Plus compat update

### PR DESCRIPTION
**Pull request by JustOff**
Dummy for Tab Mix Plus. https://forum.palemoon.org/viewtopic.php?f=16&t=8679

P.S. PageThumbs.jsm path fix [patch](https://github.com/wolfbeast/palemoon-tabgroups/tree/patch-1) merged

### CODE REVIEW

**Comment by wolfbeast** [comment]
This PR is kind of messy and has conflicts. Can you please supply a PR with only the relevant code changes and against our repo's current state?

**Comment by JustOff** [comment]
Sorry, but I'm not so familiar with github to do PR you 've requested without completely delete and start my fork from scratch ;-( 

Actually the TMP compat fix is only https://github.com/JustOff/palemoon-tabgroups/commit/ffe6791d248023e910e4d221459e7f9764ee57d3 but https://github.com/wolfbeast/palemoon-tabgroups/commit/de9a906bb8a077b9af003b79e61a269e1696abad has also applied to match current official https://www.palemoon.org/tabgroups.shtml addon binary.

**Comment by wolfbeast** [comment]
All right. I'll just grab the diff from that commit and apply it manually. Closing this PR.

**Comment by wolfbeast** [comment]
Relevant change merged in as commit 4b2b3e56498f2e72dcc6b7b0d38ac5bb95240e6b

**Comment by JustOff** [comment]
Thanks. Could you please also explain why did you leave https://github.com/wolfbeast/palemoon-tabgroups/commit/de9a906bb8a077b9af003b79e61a269e1696abad patch in separate branch, not master?

**Comment by wolfbeast** [comment]
Because i was using a bad client at the time XD
I've merged the stuff into master now.

**Pull request closed without merging**
